#!/bin/bash

# Start local development environment

set -e

echo "🚀 Starting Peptide Wiki development environment..."

# Start Supabase if not running
if ! supabase status 2>/dev/null | grep -q "API URL"; then
    echo "📦 Starting Supabase..."
    supabase start
fi

# Get Supabase credentials from status
echo "🔑 Fetching Supabase credentials..."
API_URL=$(supabase status | grep "API URL" | awk '{print $3}')
ANON_KEY=$(supabase status | grep "Publishable key" | awk '{print $3}')
SERVICE_KEY=$(supabase status | grep "Secret key" | awk '{print $3}')

# Update .env.local with current values
echo "📝 Updating .env.local..."
cat > .env.local << EOF
# Supabase Configuration (Local Development)
# Auto-generated by dev.sh - do not edit manually
PUBLIC_SUPABASE_URL=${API_URL}
PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SECRET_SUPABASE_SERVICE_KEY=${SERVICE_KEY}

# reCAPTCHA v3 (skipped on localhost)
PUBLIC_RECAPTCHA_SITE_KEY=6Lca5CgsAAAAABCKRhDlmMAfd_CzqnOoorqq4xaY
SECRET_RECAPTCHA_SECRET_KEY=6Lca5CgsAAAAAE4Q3rRO1e3Lxb0bQrP2YMSOeJTQ
EOF

echo ""
echo "✅ Supabase running:"
echo "   API:    ${API_URL}"
echo "   Studio: $(supabase status | grep 'Studio URL' | awk '{print $3}')"
echo ""

# Start the dev server
echo "🌐 Starting SvelteKit dev server..."
exec pnpm dev
